<Project>

  <PropertyGroup Condition="'$(UserSecretsId)'!=''">
    <LocalSecrets>$(LocalSecretsDir)/secrets.json</LocalSecrets>

    <LocalSecretsTemplateDir>$(MSKit_Templates)</LocalSecretsTemplateDir>
    <LocalSecretsTemplate>$(LocalSecretsTemplateDir)/$(UserSecretsId).secrets.json</LocalSecretsTemplate>
  </PropertyGroup>

</Project>
