<Project InitialTargets="CleanupLocalSecrets">

  <Target Condition="'$(LocalSecrets)'!='' AND Exists('$(LocalSecrets)')"
          Name="CleanupLocalSecrets"
          BeforeTargets="CreateLocalSecrets;Restore;CoreCompile;Build;Publish">

    <Delete Files="$(LocalSecrets)" />
  </Target>

</Project>
