<Project InitialTargets="CreateLocalSecretsTemplate;CreateLocalSecrets;MSKit_CopySecretsToProject">

  <PropertyGroup>
    <UserSecretsLinkNamePrefix Condition="'$(UserSecretsLinkNamePrefix)'==''">appsettings</UserSecretsLinkNamePrefix>
    <!-- MSKit_CopySecretsToProject: Copy secrets files to project directory. -->
    <MSKit_CopySecretsToProject Condition="'$(MSKit_CopySecretsToProject)'==''">false</MSKit_CopySecretsToProject>
    <!--@formatter:off-->
    <LocalSecretsEmptyTemplateNewBody>{
}
    </LocalSecretsEmptyTemplateNewBody>
    <!--@formatter:on-->
  </PropertyGroup>

  <ItemGroup>
    <None Condition="'$(LocalSecrets)'!=''" Include="$(LocalSecrets)">
      <Link>$(UserSecretsLinkNamePrefix).UserSecrets.json</Link>
      <!-- MSKit_CopyUserSecretsIdToOutput: Include UserSecretsId in build output. -->
      <CopyToOutputDirectory Condition="'$(MSKit_CopyUserSecretsIdToOutput)' == 'true'">Always</CopyToOutputDirectory>
      <!-- MSKit_CopyUserSecretsIdToPublish: Include UserSecretsId in publish output. -->
      <CopyToPublishDirectory Condition="'$(MSKit_CopyUserSecretsIdToPublish)' == 'true'">Always</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
  </ItemGroup>

  <Target Condition="'$(LocalSecretsTemplate)'!='' AND !Exists('$(LocalSecretsTemplate)')"
          Name="CreateLocalSecretsTemplate">
    <MakeDir Directories="$(LocalSecretsTemplateDir)" Condition="!Exists('$(LocalSecretsTemplateDir)')" />

    <WriteLinesToFile
      File="$(LocalSecretsTemplate)"
      Overwrite="true"
      Lines="$(LocalSecretsEmptyTemplateNewBody)" />

    <Message Text="The file '$(LocalSecretsTemplate)' was created." Importance="High" />
  </Target>

  <Target Condition="'$(LocalSecrets)'!='' AND !Exists('$(LocalSecrets)')"
          Name="CreateLocalSecrets" AfterTargets="CreateLocalSecretsTemplate">
    <MakeDir Directories="$(LocalSecretsDir)" Condition="!Exists('$(LocalSecretsDir)')" />

    <Copy Condition="Exists('$(LocalSecretsTemplate)')" SourceFiles="$(LocalSecretsTemplate)" DestinationFiles="$(LocalSecrets)" />

    <WriteLinesToFile
      File="$(LocalSecrets)"
      Overwrite="true"
      Condition="!Exists('$(LocalSecrets)')" Lines="$(LocalSecretsEmptyTemplateNewBody)" />
  </Target>

  <Target Condition="'$(MSKit_CopySecretsToProject)'=='true' AND '$(CopySecretsToProjectFileName)' != '' AND Exists('$(LocalSecrets)')"
          Name="MSKit_CopySecretsToProject" AfterTargets="CreateLocalSecrets">

    <Copy SourceFiles="$(LocalSecrets)" DestinationFiles="$(MSBuildProjectDirectory)/$(CopySecretsToProjectFileName)" />

    <WriteLinesToFile
      File="$(MSBuildProjectDirectory)/.gitignore"
      Overwrite="true"
      Lines="$(CopySecretsToProjectFileName)">
    </WriteLinesToFile>
  </Target>

</Project>
