<Project
  InitialTargets="CreateLocalSlnSecretsTemplateProps;CreateLocalSlnSecretsTemplateTargets;CreateLocalSlnSecretsProps;CreateLocalSlnSecretsTargets">

  <Import Condition="Exists('$(LocalSlnSecretsTargets)')" Project="$(LocalSlnSecretsTargets)" />

  <ItemGroup>
    <None Condition="'$(LocalSlnSecretsProps)'!=''" Include="$(LocalSlnSecretsProps)">
      <Link>Directory.Secrets.props</Link>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Condition="'$(LocalSlnSecretsTargets)'!=''" Include="$(LocalSlnSecretsTargets)">
      <Link>Directory.Secrets.targets</Link>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <LocalSlnSecretsEmptyTemplateNewBody>&lt;Project&gt;
&lt;/Project&gt;
    </LocalSlnSecretsEmptyTemplateNewBody>
  </PropertyGroup>

  <Target Condition="'$(LocalSlnSecretsTemplateProps)' != '' AND !Exists('$(LocalSlnSecretsTemplateProps)')"
          Name="CreateLocalSlnSecretsTemplateProps">
    <MakeDir Directories="$(LocalSlnSecretsTemplateDir)" Condition="!Exists('$(LocalSlnSecretsTemplateDir)')" />

    <WriteLinesToFile
      File="$(LocalSlnSecretsTemplateProps)"
      Overwrite="true"
      Lines="$(LocalSlnSecretsEmptyTemplateNewBody)" />

    <Message Text="The file '$(LocalSlnSecretsTemplateProps)' was created." Importance="High" />
  </Target>

  <Target Condition="'$(LocalSlnSecretsTemplateTargets)' != '' AND !Exists('$(LocalSlnSecretsTemplateTargets)')"
          Name="CreateLocalSlnSecretsTemplateTargets">
    <MakeDir Directories="$(LocalSlnSecretsTemplateDir)" Condition="!Exists('$(LocalSlnSecretsTemplateDir)')" />

    <WriteLinesToFile
      File="$(LocalSlnSecretsTemplateTargets)"
      Overwrite="true"
      Lines="$(LocalSlnSecretsEmptyTemplateNewBody)" />

    <Message Text="The file '$(LocalSlnSecretsTemplateTargets)' was created." Importance="High" />
  </Target>

  <Target Condition="'$(LocalSlnSecretsProps)' != '' AND !Exists('$(LocalSlnSecretsProps)')"
          Name="CreateLocalSlnSecretsProps" AfterTargets="CreateLocalSlnSecretsTemplateProps">
    <MakeDir Directories="$(LocalSlnSecretsDir)" Condition="!Exists('$(LocalSlnSecretsDir)')" />

    <Copy Condition="Exists('$(LocalSlnSecretsTemplateProps)')" SourceFiles="$(LocalSlnSecretsTemplateProps)"
          DestinationFiles="$(LocalSlnSecretsProps)" />

    <WriteLinesToFile
      File="$(LocalSlnSecretsProps)"
      Overwrite="true"
      Condition="!Exists('$(LocalSlnSecretsProps)')" Lines="$(LocalSlnSecretsEmptyTemplateNewBody)" />
  </Target>

  <Target Condition="'$(LocalSlnSecretsTargets)' != '' AND !Exists('$(LocalSlnSecretsTargets)')"
          Name="CreateLocalSlnSecretsTargets" AfterTargets="CreateLocalSlnSecretsTemplateTargets">
    <MakeDir Directories="$(LocalSlnSecretsDir)" Condition="!Exists('$(LocalSlnSecretsDir)')" />

    <Copy Condition="Exists('$(LocalSlnSecretsTemplateTargets)')" SourceFiles="$(LocalSlnSecretsTemplateTargets)"
          DestinationFiles="$(LocalSlnSecretsTargets)" />

    <WriteLinesToFile
      File="$(LocalSlnSecretsTargets)"
      Overwrite="true"
      Condition="!Exists('$(LocalSlnSecretsTargets)')" Lines="$(LocalSlnSecretsEmptyTemplateNewBody)" />
  </Target>

</Project>
