<Project>

  <PropertyGroup>
    <MSKit_SlnSecretsId Condition="'$(MSKit_SlnSecretsId)'==''">$(MSKit_SlnFileName)</MSKit_SlnSecretsId>
    <!-- MSKit_UseSlnSecretsProps: Import solution-level secrets .props file. -->
    <MSKit_UseSlnSecretsProps Condition="'$(MSKit_UseSlnSecretsProps)'==''">False</MSKit_UseSlnSecretsProps>

  </PropertyGroup>

  <PropertyGroup Condition="'$(MSKit_SlnSecretsId)'!=''">
    <LocalSlnSecretsDir>$(MSKit_LocalSecretsBaseDirectory)$(MSKit_SlnSecretsId)</LocalSlnSecretsDir>
    <LocalSlnSecretsProps Condition="'$(MSKit_UseSlnSecretsProps)'=='True'">$(LocalSlnSecretsDir)/Directory.Secrets.props</LocalSlnSecretsProps>

    <LocalSlnSecretsTemplateDir>$(MSKit_Templates)</LocalSlnSecretsTemplateDir>
    <LocalSlnSecretsTemplateProps Condition="'$(MSKit_UseSlnSecretsProps)'=='True'">$(LocalSlnSecretsTemplateDir)/Directory.Secrets.props</LocalSlnSecretsTemplateProps>
  </PropertyGroup>

  <Import Condition="Exists('$(LocalSlnSecretsProps)') AND '$(MSKit_IsDevEnv)'=='True'" Project="$(LocalSlnSecretsProps)" />

  <PropertyGroup>
    <!-- MSKit_UseSlnSecretsTargets: Import solution-level secrets .targets file. -->
    <MSKit_UseSlnSecretsTargets Condition="'$(MSKit_UseSlnSecretsTargets)'==''">False</MSKit_UseSlnSecretsTargets>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSKit_SlnSecretsId)'!=''">
    <LocalSlnSecretsTargets Condition="'$(MSKit_UseSlnSecretsTargets)'=='True'">$(LocalSlnSecretsDir)/Directory.Secrets.targets</LocalSlnSecretsTargets>

    <LocalSlnSecretsTemplateTargets Condition="'$(MSKit_UseSlnSecretsTargets)'=='True'">$(LocalSlnSecretsTemplateDir)/Directory.Secrets.targets</LocalSlnSecretsTemplateTargets>
  </PropertyGroup>

</Project>
