<Project InitialTargets="CleanupLocalSlnSecretsProps;CleanupLocalSlnSecretsTargets">

  <Target Condition="'$(LocalSlnSecretsProps)'!='' AND Exists('$(LocalSlnSecretsProps)')"
          Name="CleanupLocalSlnSecretsProps"
          BeforeTargets="CreateLocalSlnSecretsProps;Restore;CoreCompile;Build;Publish">

    <Delete Files="$(LocalSlnSecretsProps)" />

  </Target>

  <Target Condition="'$(LocalSlnSecretsTargets)'!='' AND Exists('$(LocalSlnSecretsTargets)')"
          Name="CleanupLocalSlnSecretsTargets"
          BeforeTargets="CreateLocalSlnSecretsTargets;Restore;CoreCompile;Build;Publish">

    <Delete Files="$(LocalSlnSecretsTargets)" />

  </Target>

</Project>
