<Project>

  <PropertyGroup>
    <Nullable Condition="'$(Nullable)'==''">enable</Nullable>
    <ImplicitUsings Condition="'$(ImplicitUsings)'==''">enable</ImplicitUsings>
    <LangVersion Condition="'$(LangVersion)'==''">latest</LangVersion>
    <EnforceCodeStyleInBuild Condition="'$(EnforceCodeStyleInBuild)'==''">True</EnforceCodeStyleInBuild>
    <GeneratePackageOnBuild Condition="'$(GeneratePackageOnBuild)'==''">False</GeneratePackageOnBuild>
    <MSKit_IncludeCodeAnalysisGlobalUsings Condition="'$(MSKit_IncludeCodeAnalysisGlobalUsings)'==''">True</MSKit_IncludeCodeAnalysisGlobalUsings>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)product.props" />

  <Import Condition="Exists('$(MSKit_SlnFileDirectory)Directory.Version.props')"
          Project="$(MSKit_SlnFileDirectory)Directory.Version.props" />

</Project>
