<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Build Mermaid flowchart diagrams from .NET code and render them as Mermaid text.</Description>
    <PackageTags>mermaid;diagram;flowchart;markdown</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DragoAnt.Shared\DragoAnt.Shared.csproj"/>
  </ItemGroup>

</Project>
